from typing import Protocol


class TextServiceInterface(Protocol):
    async def detect_encoding(self, file_path: str) -> str: ...
    async def validate_encoding(self, file_path: str, encoding: str) -> bool: ...
    async def extract_text(self, file_path: str, encoding: str) -> str: ...
